name: Franklin, Denney, Ward & Dryer P.L.C.
url: http://fdwd.jayperryworks.com
baseurl: /fdwd

markdown: redcarpet
pygments: true

exclude: ["README.md", "config.rb", ".sublime-project", ".sublime-workspace", "Guardfile", "Gemfile", "Gemfile.lock", ".sass-cache"]