name: Franklin, Denney, Ward & Dryer P.L.C.
url: http://fdwd.jayperryworks.com
baseurl: 

markdown: redcarpet
pygments: true

exclude: ["README.md", "config.rb", ".sublime-project", ".sublime-workspace", "Guardfile", "Gemfile", "Gemfile.lock", ".sass-cache", "node_modules", "package.json", "Gruntfile.js", "bower.json", ".bowerrc"]

# asset paths
assets:
  img: 'assets/images/'
  css: 'assets/css/'
  js: 'assets/js/'
  fonts: 'assets/fonts/'
  bower: '_bower_components/'